### ISSUE TITLE
Strip out certain attributes

### ISSUE THREAD

**Issue by soluml** [apostrophecms/sanitize-html#104]
I'd like to allow all attributes with a few exceptions.  Is this possible?

**Comment by boutell** [comment]
Not currently. A pull request for a disallowedAttributes option would
certainly be considered... however I wonder if you've thoroughly considered
all the things that can go wrong when you try to prove a negative (:

On Wed, Apr 6, 2016 at 12:29 PM, Benjamin Solum <notifications@github.com>
wrote:

> I'd like to allow all attributes with a few exceptions. Is this possible?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/104>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by soluml** [comment]
I guess I see this tool as having broader applications than its primary use of sanitizing user input. I was working on a build process with React/JSX to generate HTML. The HTML generated was correct but had some extra attributes that weren't needed.  If I had a blacklist (instead of just a whitelist), I could've used this tool to clean those up and be on my way.

The same is true for tags. I think there are applications out there where the incoming HTML is trusted, just needs a little cleaning/tweaking. I think these applications could benefit more from a blacklist than a whitelist.

Just a thought!  I know I'm trying to use the tool out of it's typical use case :)

**Comment by boutell** [comment]
Yes (: But those options are pretty benign and easy to implement, so I
would consider those PRs.

On Thu, Apr 7, 2016 at 1:18 PM, Benjamin Solum <notifications@github.com>
wrote:

> I guess I see this tool as having broader applications than its primary
> use of sanitizing user input. I was working on a build process with
> React/JSX to generate HTML. The HTML generated was correct but had some
> extra attributes that weren't needed. If I had a blacklist (instead of just
> a whitelist), I could've used this tool to clean those up and be on my way.
>
> The same is true for tags. I think there are applications out there where
> the incoming HTML is trusted, just needs a little cleaning/tweaking. I
> think these applications could benefit more from a blacklist than a
> whitelist.
>
> Just a thought! I know I'm trying to use the tool out of it's typical use
> case :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/104#issuecomment-207003184>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
