### ISSUE TITLE
exclusiveFilter - a check to see if HREF in Anchor link is empty

### ISSUE THREAD

**Issue by antipath** [apostrophecms/sanitize-html#107]
cleanHtml = (markup) => {
    return sanitizeHtml(markup, {
      allowedTags: ['p', 'b', 'i', 'em', 'a', 'strong', 'sup', 'sub', 'h2', 'h3', 'h4', 'h5', 'h6', 'ul', 'li', 'ol'],
      allowedAttributes: {'*': [], 'a': ['href', 'target']},
      transformTags: {'h1': 'h2'},
      exclusiveFilter: function(frame) {
        return frame.tag === 'a' && !frame.attribs.href.trim();
      }
    });
  }

is there a way to perverse the text even tho the Anchor tag is stripped?

**Comment by abea** [comment]
You could check it with `frame.text` in that `exclusiveFilter` function.
