### ISSUE TITLE
namespacing css using the exclusive filter

### ISSUE THREAD

**Issue by eliotc1986** [apostrophecms/sanitize-html#116]
I am trying to use the exclusive filter to namespace css, but I can't get it to return the updated `frame.text`

``` js
var _cleanHtml = function(srcCode) {
    var cleanHTML = sanitizeHtml(srcCode, {
      allowedTags: config.allowedTags, // array of html elements, which includes 'style' tag
      allowedAttributes: false,
      exclusiveFilter: function(frame) {
        if(frame.tag === 'style') {
          frame.text = _namespaceCss(frame.text);
          console.log(frame.text); // contains namespaced css
        }
      }
    });

   console.log(cleanHTML); // contains non-namespaced css :(

    return cleanHTML;
  };
```

I noticed the `frame` object contains a function called `updateParentNodeText`. Is is possible to use this to update the `frame.text`?

**Comment by abea** [comment]
`exclusiveFilter` is not meant to alter the `frame` object. It should return a boolean value that tells `sanitize-html` whether to filter the tag out.
