### ISSUE TITLE
exclusiveFilter: html content of frame

### ISSUE THREAD

**Issue by Diokuz** [apostrophecms/sanitize-html#118]
I have the following html:

``` html
<p>text</p>
<p><img ... /></p>
<p></p>
```

I want to remove only third `p`, but not first and second.
How can I do that?

exclusiveFilter `frame.text` gives me an empty string for second `p`, but I cannot filter it because it has an image.

**Comment by marvindanig** [comment]
Did you find a solution for this? I'm having the problem.

**Comment by Diokuz** [comment]
No)

**Comment by pablocuesta92** [comment]
This worked for me:
```
        exclusiveFilter: function (frame) {
          // removing empty p tags
          if (frame.tag === 'img') {
            frame.text += ' '
            frame.updateParentNodeText()
          }
          return frame.tag === 'p' && !frame.text
        },
```
