### ISSUE TITLE
Possible to strip out just JavaScript?

### ISSUE THREAD

**Issue by jd327** [apostrophecms/sanitize-html#124]
The `<script>` tag is pretty straightforward, but how about leaving all HTML as is and stripping out only [global event handlers](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers), like `onclick`?

**Comment by schulm** [comment]
I'm looking for a solution, too.

**Comment by boutell** [comment]
You would also have to clobber any javascript: URLs.

We would look at a PR for an option that just disabled all JavaScript.

**Comment by schulm** [comment]
Im in the browser, I was going with this solution: https://vanillajstoolkit.com/helpers/sanitizehtml/
