### ISSUE TITLE
naughtyHref always allows hrefs with empty schemes

### ISSUE THREAD

**Issue by dbkr** [apostrophecms/sanitize-html#132]
This means that links of the form, "//example.com/nasty.js" will always be accepted, essentially allowing links to whatever scheme to host page is served over. In practice, this means it's possible to link to http(s) content even if neither 'http' not 'https' are in allowedSchemes / allowedSchemesByTag.

**Comment by boutell** [comment]
Hmm.

"Protocol-relative" is not a scheme. But it is a thing that someone might reasonably want to disable, yes.

I guess it would make sense to provide an option to cover this:

`allowProtocolRelative`

Which would be `true` by default, for backwards compatibility.

A PR would certainly be welcome.

**Comment by simison** [comment]
This can probably be closed since `allowProtocolRelative` is now in.

https://github.com/punkave/sanitize-html/commit/4c229fbbc9c269236b571dcbf834dc7c0ea19012
