### ISSUE TITLE
Adding a demo playground page would help

### ISSUE THREAD

**Issue by yairEO** [apostrophecms/sanitize-html#147]
Suggestion: I would love to be able to try some input and see the code's output because I will spend any of my time integrating this into my code.

**Comment by simison** [comment]
Here's short tester in case it's useful for someone. :-)

```
mkdir sanitizeHtmlTest && cd sanitizeHtmlTest
npm i sanitize-html
node -p -e "require('sanitize-html')('<br><img>', { allowedTags: ['br'] })"
→ <br />
```

**Comment by csoni111** [comment]
You may use [npm.runkit.com](https://npm.runkit.com/sanitize-html) to play around!
