### ISSUE TITLE
Strip characters after </html>

### ISSUE THREAD

**Issue by afhole** [apostrophecms/sanitize-html#149]
Word 2010 sometimes adds strange chars after `</html>` e.g. the unicode replacement character (`\ufffd`)
I am manually removing them with `replace(/<\/html>[\s\S]*/, '</html>')` for now

**Comment by andpor** [comment]
I had the same issue and created a PR to fix this https://github.com/punkave/sanitize-html/pull/166. Would be great it this got merged soon.

**Comment by abea** [comment]
I'll close this. The problem is discussed more in #164 and there's a PR in review.
