### ISSUE TITLE
Removing elements with a certain class

### ISSUE THREAD

**Issue by souljacker** [apostrophecms/sanitize-html#150]
Let's say I have a big chunk of HTML and I only to remove all divs with the class 'test' from that text. I don't want to keep the div or its content, so I think allowedClasses wouldn't help. Instead, I need to remove it totally. 

Is there a way I cn do this with sanitize-html or I'll have to rely on regex?

**Comment by andpor** [comment]
Maybe you can accomplish this in two passes...in first pass you replace the div tag with matching class with some other tag you invent. You add this new pseudo class to allowed tags. 

In second pass you config this pseudo tag as nonTextTag and do not include it in allowed tags.

I have not tried this myself but it may work :)

**Comment by abea** [comment]
This should be possible with `exclusiveFilter` https://github.com/apostrophecms/sanitize-html/#filters
