### ISSUE TITLE
Add missing paragraphs to string

### ISSUE THREAD

**Issue by AlecRust** [apostrophecms/sanitize-html#152]
Is there a way to add missing paragraphs to a string if none exist with sanitize-html?

i.e. if string is `<p>some text...</p>` leave it alone, if it's `some text...` turn it in to `<p>some text...</p>`.

**Comment by andpor** [comment]
Now there is ...I added this feature by adding text parameter to transformTags . Allows you to check this and modify text exactly as you as implying. This has not yet been merged though...

PR https://github.com/punkave/sanitize-html/pull/166

**Comment by andpor** [comment]
I added a tag to textFilter. So if your text is sitting there lonely without any tags inside `<body>` tag, you would get a callback with this text and "body: tag. Although i had not tried it with producing a new tag you could give it a shot in you local and see if it works ..

PR https://github.com/punkave/sanitize-html/pull/166

**Comment by andpor** [comment]
I did a quick test and looks like yes, from textFilter you can in fact return an html tag with text...even without my PR(although with the PR in place you would know which tag this text is a child of.. :)

**Comment by mqtik** [comment]
I'm trying this as well.

@andpor can you post an example?

**Comment by andpor** [comment]
> I'm trying this as well.
> 
> @andpor can you post an example?

I wish I could but my memory is getting worse with age so can't go back as far as 2017 :)

**Comment by abea** [comment]
The `tag` is a parameter on `textFilter`, so this should be doable.
