### ISSUE TITLE
Allow all css classes on selected tag

### ISSUE THREAD

**Issue by andrei-sheina** [apostrophecms/sanitize-html#155]
I use PostCSS in my project, and all of my css classes looks like this - `user-name--3sKPh` and it's impossible to allow such css classes as allowed. I tried to use wildcard (`allowedClasses: { 'span': ['*'] }` and `allowedClasses: { 'span': ['css-class--*'] }`) but it doesn't work. So it would be very nice to add ability to allow all css classes for selected tag, or to use wildcard in css class name.

**Comment by simison** [comment]
Would it work to set it as an ID?

**Comment by andrei-sheina** [comment]
@simison i don't understand your question. I made it work by assigning allowedClass as `allowedClasses: { 'span': [styles.cssClass] })` but it works in my workaround and may not work in someone else's workaround. So it's still a nice feature to have.

**Comment by abea** [comment]
If you simply add `'class'` in an element's `allowedAttributes` option it should allow any class for that element.
