### ISSUE TITLE
Replacing br tags with p

### ISSUE THREAD

**Issue by andpor** [apostrophecms/sanitize-html#162]
This is a question.

I have a sample html input that looks like this

`"<p>some text<br> <br> and more text</p>"`

Ideally what I am looking for is a way to replace this br sequence with closing p and opening p so it looks like this:

`"<p>some text</p> <p> and more text</p>"`

Is this feasible using sanitizeHtml at all?

BTW  - this is really an awesome library - nothing else like it. Very helpful and flexible.

**Comment by abea** [comment]
Duplicate of #52
