### ISSUE TITLE
Limit allowed mime types for data URIs?

### ISSUE THREAD

**Issue by fredboyle** [apostrophecms/sanitize-html#165]
Is there currently a way to limit the mime types allowed for data URIs?

i.e. If we'd like to whitelist only `data:image/*` and `data:text/*` or only certain encoded image formats (gif, jpg, png).

Thanks.

**Comment by Vikt0rKr** [comment]
Hi, i've come up with this solution: add field exclusiveFilter in the options object, set all validations you need inside of it:
```exclusiveFilter(frame) {
      return (
        // any tag you want
        frame.tag === 'img' &&
        frame.attribs.src &&
        // any attrib you want to check
        frame.attribs.src.search(/data:text/gi) < 0 &&
        frame.attribs.src.search(/data:image/gi) < 0
      );
    },```

**Comment by boutell** [comment]
That works, ish, although I'm guessing it could be gamed... I'd certainly take a PR to do this correctly with a simple option.
