### ISSUE TITLE
Allow setting of what are allowed values for attributes.

### ISSUE THREAD

**Issue by ml-dublin** [apostrophecms/sanitize-html#203]
Question: can I set what are allowed values for attributes?

For example, we are currently using OWASP/java-html-sanitiser in our old Java project and we have the following in our configuration:
```xml
<allowSpecificAttributeListOnElements>
		<element name="iframe" />
		<elementAttribute name="sandbox" />
		<attributeValue value="allow-popups" />
		<attributeValue value="allow-scripts" />
		<attributeValue value="allow-same-origin" />
		<delimiter value=" " />
	</allowSpecificAttributeListOnElements>
```

This means that `sandbox` is an allowed attribute of `iframe` and `sandbox` has allowed values: `allow-popups`, `allow-scripts` and `allow-same-origin`.

The easy part is done, i.e. `sandbox` is an allowed attribute of `iframe`, but can I enforce the specific values?

Currently I am trying to enforce something similar with _sanitize-html_.

Thanks in advance for any input you have in solving this.

**Comment by boutell** [comment]
There isn't an easy way to do that at the moment. A PR would be welcome. Probably something like:

`allowedAttributes: { h1: [ { name: 'class', values: [ 'one', 'two', 'three' ] }, 'title' ] }`

Notice that intermixing the existing style (plain attribute names) with these objects that specify allowed values would be permitted.

It would also make sense to allow a regular expression or function to be passed via an `allow` property, as an alternative to a flat array of allowed vlaues.

**Comment by berndsi** [comment]
It would be great if one could restrict any URLs in (any) attribute values to certain host or domain names or relative URLs. Or allow regular expressions for this.

**Comment by ml-dublin** [comment]
How about something like this:
```javascript
allowedAttributeSpecificValues: {
  iframe: [
    {
      sandbox: [ 'allow-popups', 'allow-scripts', 'allow-same-origin' ]
    }
  ]
}
```
This allows setting specific values for attributes on specific elements, it is also easier for users to set specific values for the default allowedAttributes.

**Comment by boutell** [comment]
I see what you mean, but I think we'd wind up needing the flexibility of my proposal, in particular the capacity to mix and match "this attribute is just plain allowed," "this attribute is allowed with certain values," and "this attribute gets custom validation." Writing them all in an array together helps keep your thoughts about that element together.

**Comment by ml-dublin** [comment]
Just an f.y.i. that this works for me, lets my tests pass, basically it takes out the current checks from the if statement and adds a check for attribute values.
```javascript
    each(options.allowedAttributes, function(attributes, tag) {
      allowedAttributesMap[tag] = [];
      var globRegex = [];
      attributes.forEach(function(obj) {
        if(isString(obj) && obj.indexOf('*') >= 0) {
          globRegex.push(quoteRegexp(obj).replace(/\\\*/g, '.*'));
        } else {
          allowedAttributesMap[tag].push(obj);
        }
      });
      allowedAttributesGlobMap[tag] = new RegExp('^(' + globRegex.join('|') + ')$');
    });

...

          var passedAllowedAttributesMapCheck = false;
          if (!allowedAttributesMap ||
            (has(allowedAttributesMap, name) && allowedAttributesMap[name].indexOf(a) !== -1 ) ||
            (allowedAttributesMap['*'] && allowedAttributesMap['*'].indexOf(a) !== -1 ) ||
            (has(allowedAttributesGlobMap, name) && allowedAttributesGlobMap[name].test(a)) ||
            (allowedAttributesGlobMap['*'] && allowedAttributesGlobMap['*'].test(a))) {    
              passedAllowedAttributesMapCheck = true;
          } else if (allowedAttributesMap && allowedAttributesMap[name]) {
            for (const o of allowedAttributesMap[name]) {
              if (isPlainObject(o) && o.name && (o.name === a)) {
                passedAllowedAttributesMapCheck = true;
                // now need to verify the value is allowed
                const splitStrArray = value.split(' ');
                var newValue = '';
                for (const s of splitStrArray) {
                  if (o.values.indexOf(s) !== -1) {
                    if (newValue === '') {
                      newValue = s;
                    } else {
                      newValue += ' ' + s;
                    }
                  }
                }
                value = newValue;
              }
            }
          }
          if (passedAllowedAttributesMapCheck) {
            if (options.allowedSchemesAppliedToAttributes.indexOf(a) !== -1) {
```
passing in options like this:
```javascript
        allowedAttributes: {
          iframe: [ 
            {
              name: 'sandbox',
              values: ['allow-popups', 'allow-same-origin', 'allow-scripts']
            },
            'allowfullscreen'
          ]
        }
```
Just need to figure out the git side to merge it as I had issues with #201.
