### ISSUE TITLE
The iframe src code sample from the Iframe Filters section of https://www.npmjs.com/package/sanitize-html is not working

### ISSUE THREAD

**Issue by iambrosie** [apostrophecms/sanitize-html#215]
Hi,

I am trying to run the following code sample:
`clean = sanitizeHtml('<p><iframe src="https://www.youtube.com/embed/nykIhs12345"></iframe><p>', {`
`  allowedTags: [ 'p', 'em', 'strong', 'iframe' ],`
`  allowedClasses: {`
`    'p': [ 'fancy', 'simple' ],`
`    'iframe': ['src']`
`  },`
`  allowedIframeHostnames: ['www.youtube.com', 'player.vimeo.com']`
`});`

which is provided as a sample for using Iframe Filters here: https://www.npmjs.com/package/sanitize-html.
The output I get after running the aforementioned code sample is:

`me@my:~/path/to/folder$ node index.js`
`<p><iframe></iframe></p><p></p>`

The expected output is:
`<p><iframe src="https://www.youtube.com/embed/nykIhs12345"></iframe><p>`

The sanitize-html version used is 1.18.2, together with node version 1.8.2

Kind regards,
Ionut Ambrosie

**Comment by boutell** [comment]
@ryan-veris would you please take a look at this since it's your contribution? Thanks.

**Comment by ryan-verys** [comment]
Hi @iambrosie this may be a misprint in the docs, `src` is an attribute not a class. Instead of

`allowedClasses: {
'iframe': ['src']
},`

can you try 

`allowedAttributes: {
'iframe': ['src']
},`

and report your results?

**Comment by ryan-verys** [comment]
Ok I'll update the docs. Sorry for the confusion!

**Comment by iambrosie** [comment]
No worries. Glad it works now.
