### ISSUE TITLE
transform a self-closing tag into a tag that needs to be closed

### ISSUE THREAD

**Issue by sebasromano-zz** [apostrophecms/sanitize-html#219]
We are using this library with custom tags. When I tried to transform a custom self-closing tag into a tag that needs to be closed I had an unexpected result. The problem also happens when we transform a standard self-closing tag like <img />.

Example:
```javascript
var options = {
 selfClosing: sanitizeHtml.defaults.selfClosing.concat(['youtube']),  
 transformTags: {  
   youtube: function(tagName, attribs) {
     return {  
        tagName: 'iframe',  
        attribs: {  
          width: "560",  
          height: "315",  
          src: `https://www.youtube.com/embed/${attribs.youtubeid}?
          modestbranding=0&amp;showinfo=0&amp;rel=0`  
        }  
      }  
  }  
}  
var content = '<h1>Title</h1><youtube id="EXAMPLEID" /><h2>Subtitle</h2><p>Another content</p>';
var sanitizedHtml = sanitizeHtml(content, options);
console.log(sanitizedHtml);
```
Output:
```html
<h1>Title</h1>
<iframe src="https://www.youtube.com/embed/EXAMPLEID?
         modestbranding=0&amp;showinfo=0&amp;rel=0" width="560" height="315">
<h2>Subtitle</h2>
<p>Another content</p>
</iframe>
```
As you an see the h2 and p tags are inner <iframe> tag.
I created a diff to solve this issue, could you give me access to create a pull request?

**Comment by sebasromano** [comment]
I'm sorry, I opened this ticket before with my corporate email. This is the correct one. Thanks

**Comment by abea** [comment]
I don't think this is a use case for `sanitize-html`. As the name and description suggests, this is "a simple HTML sanitizer." More complex DOM transformations are outside of its purview.
