### ISSUE TITLE
Suggestion for Tidy-map as extra-documentation

### ISSUE THREAD

**Issue by ppKrauss** [apostrophecms/sanitize-html#236]
A table "from Tidy parameter | to sanitize-html parameter".

There are a lot of legacy system using ([example](http://php.net/manual/en/book.tidy.php)), and direct users of [Tidy](http://www.html-tidy.org): <br/> http://api.html-tidy.org/tidy/quickref_5.6.0.html

So, will be useful for mantainers that need to migrate from Tidy... or for help, as complementar glossary. Will be also a good checklist (!) for sanitize-html.  

PS: I can help to build ~50%.

**Comment by boutell** [comment]
I could see something like a separate `.md` file with the project called `tidy migration guide`. I don't feel there's a particularly pressing need to put time into it on this end given that this is the first request, but it's a contribution we'd gladly accept.
