### ISSUE TITLE
Purify special characters

### ISSUE THREAD

**Issue by outOFFspace** [apostrophecms/sanitize-html#263]
Is it possible to escape custom specail characters? For example:
`&#8232; &#8233; &#2029;`
These entities will break your JSON.
[Jsfiddle](https://jsfiddle.net/vovchuck_bogdan/nc5qgwhm/)

**Comment by boutell** [comment]
I can see that those are bad in the context of JSON, which is a really common place to be when using this module. It could make sense to bake in autoescaping of things that JSON is unable to handle at all. Alternatively you could do it in a few lines after the fact, of course.

**Comment by outOFFspace** [comment]
For those, who will be searching on how to bit it:
`replaceSpecialChars(str) {
        const chars = [8232, 8233, 2029];
        let newStr = '';
        for (let d = 0; d < str.length; d++) {
            if (chars.indexOf(str.charCodeAt(d)) === -1) {
                newStr += str[d];
            }
        }
        return newStr;
    },`
