### ISSUE TITLE
Sanitization not applied recursively

### ISSUE THREAD

**Issue by bkimminich** [apostrophecms/sanitize-html#29]
Sanitization is not applied recursively, leading to a vulnerability to certain masking attacks. Example:

`I am not harmless: <<img src="csrf-attack"/>img src="csrf-attack"/>` is sanitized to `I am not harmless: <img src="csrf-attack"/>`

Mitigation: Run sanitization recursively until the input html matches the output html.

**Comment by boutell** [comment]
This issue has been resolved better through the use of the decodeEntities: true option of htmlparser2. Recursive invocation is no longer required to pass the test suite.
