### ISSUE TITLE
[Request] Allow Rendering Tags as Text

### ISSUE THREAD

**Issue by martinmckenna** [apostrophecms/sanitize-html#291]
Related: #169

I'd like a way to opt to render a script tag as text, rather than remove it completely. Currently, I'm implementing the following logic

```js
sanitize(text, {
    allowedTags: [...allowedHTMLTags, 'script'],
    nonTextTags: ['style', 'textarea'],
    /** this is basically just converting script tags to text */
    transformTags: {
      script: (tagName, attrs: Record<string, string>) => {
        /** 
         * get all attributes of the script tag and recreate them as they were typed 
         * i.e src="hello.js"
         */
        const attrsAsString = Object.keys(attrs).reduce((accum, eachKey) => {
          return `${accum} ${eachKey}="${attrs[eachKey]}"`;
        }, '');

        /** return the script tag as text inside a p tag */
        return {
          tagName: 'p',
          text: `&lt;${tagName}${attrsAsString}&gt;&lt;/${tagName}&gt;`,
          attribs: {}
        };
      }
    }
```

The issue here is:

1. I don't have access to the text within the `script` tag, so if I'm sanitizing `<script>alert('hello')</script>` I lose the text inside and can't render the user input as text correctly.
2. I run into issues when sanitizing something like `<script>alert('hello world');</script>`
   * this ends up rendering as `<p><script><script></script></script></p>`

I'm hoping in the future to just pass an option that will allow me to render script tags as text.

**Comment by arrants8** [comment]
Bump on this. Would be very helpful :)

**Comment by abea** [comment]
Have you explored the `disallowedTagsMode: 'escape'` option?
