### ISSUE TITLE
ampersand(&) is HtmlEncoded. Is there way to opt out it

### ISSUE THREAD

**Issue by dyang-branch** [apostrophecms/sanitize-html#296]
Hi Team,
 Is there a way to opt out the HTMLEncode ampersand(&) in the sanitization
For example
`<a href='http://example.com/index.php?query=test&query2=test2&query3=test3'>Query&Query</a>`

will be sanitized to
`<a href=\"http://example.com/index.php?query=test&amp;query2=test2&amp;query3=test3\">Query&amp;Query</a>`

I don't want to HTMLEncode it. Is there a way to do so?

Thanks
Daniel

**Comment by boutell** [comment]
No, we generate strictly valid markup.
