### ISSUE TITLE
Don't escape unescaped html entities

### ISSUE THREAD

**Issue by saveman71** [apostrophecms/sanitize-html#297]
I feel there is a weird behavior here:

```js
const s = require('sanitize-html');
s('Test & other&nbsp;test');
// 'Test &amp; other test'
```

I'm aware that setting `decodeEntites` to `false` "kinda" solves that incoherence by making everything escaped:

```js
s('Test & other&nbsp;test', {parser: {decodeEntities: false}});
// 'Test &amp; other&nbsp;test'
```

Is there a way though to have `'Test & other test'` ? (everything decoded and not re-escaped).

My concern is that I'm throwing the output to `ejs`'s `<%=` tags that _will_ escape again, so `&amp;` will be double escaped to `&amp;amp;`.

EDIT: I feel there is a better title to that issue, feel free to change/suggest

**Comment by boutell** [comment]
This module's output is valid HTML with a valid representation of the same characters that went in. Your nonbreaking space is still a nonbreaking space, it's just represented as the appropriate unicode character in your output example. Preserving exactly the same representation that happened to be used in the input is not supported.

**Comment by saveman71** [comment]
Thanks for the prompt answer! I understand the reason and why you closed the issue. I ended up solving it by using lodash's `_.unescape` function on the output (even though it may seem a bit counter productive and unsafe I agree!)

```js
const s = require('sanitize-html');
const _ = require('lodash');

 _.unescape(s('Test & other&nbsp;test<script>Hello</script><strong>Hi</strong>'))
// 'Test & other test<strong>Hi</strong>'
```

This fulfills my need of being able to parse / filter unwanted tags + keeping raw characters. I feel like I need to explain a bit more the usage in case people are wondering:

We use https://github.com/i18next/i18next for our translations, and some translations _can_ contain a limited set of HTML (known which one in advance). `sanitize-html` is set as a post processing for all the translation keys (even the ones without HTML).

Then, when we want to use a translation, we use `ejs`:

```
<%= t('translation.without.html') %>
```

`<%=` escapes all the `<`, `&`, `>`, etc. so we need to have utf-8 characters in input.

```
<%- t('translation.with.html') %>
```

Here no escaping is done (`<%-`) so we can have HTML code (and here `&amp;` would have been fine, even if it is thus removed with `_.unescape`).

Hope this can be useful to somebody in the future!
