### ISSUE TITLE
Chinese Translation Documents 中文翻译文档

### ISSUE THREAD

**Issue by MrLeeGit** [apostrophecms/sanitize-html#302]
可以参阅中文翻译文档
https://www.jianshu.com/p/6992e5edb25d

**Comment by boutell** [comment]
Hi @MrLeeGit, I apologize for my lack of Chinese reading skills.

It looks like you are offering a translation of the documentation.

The challenge for us will be to find someone to review it properly.

Thank you for contributing!

**Comment by abea** [comment]
We'll be glad if Chinese speakers find that and it helps them. Unless we can ensure that they stay updated as the core documentation changes I don't think we can officially link to them for now.
