### ISSUE TITLE
Different handling of rel="noopener noreferrer" inside stringified context

### ISSUE THREAD

**Issue by cschwaderer** [apostrophecms/sanitize-html#303]
I pass strings through sanitze-html which are actually stringified JSON objects containing some HTML at some properties.

After having added `rel="noopener noreferrer"` to all `a` tags I discovered something strange: The attribute is handled differently depending on whether I allow all tags and attributes in sanitize-html or just some specificly.

Consider the code below:

```
const sanitizeHtml = require('sanitize-html');

var myHTMLString = '<a href="http://harmless" target="_blank" rel="noopener noreferrer">harmless page</a>';

var myObject = {
    "foo": myHTMLString    
}

var myObjectAsString = JSON.stringify(myObject);

console.log(myObjectAsString);

var sanitizedStrict = sanitizeHtml(myObjectAsString, {
    allowedTags: ['a'],
    allowedAttributes: {
      '*': [ 'href','target', 'rel']
    },
    allowedSchemes: ['http']
  });

var sanitizeAllowAll = sanitizeHtml(myObjectAsString, {
    allowedTags: false,
    allowedAttributes: false,
    allowedSchemes: ['http', 'https', 'ftp', 'mailto','data','javascript']
  });

console.log(sanitizedStrict);
console.log(sanitizeAllowAll);
```
Everything works as expected, if I directly put `myHTMLString` into sanitze-html.
However, after passing `myObjectAsString` the behaviour is different.

I get 

`{"foo":"<a href="\&quot;http://harmless\&quot;" target="\&quot;_blank\&quot;" rel="\&quot;noopener">harmless page</a>"}` for `sanitizedStrict` (allowing only something)

and

`{"foo":"<a href="\&quot;http://harmless\&quot;" target="\&quot;_blank\&quot;" rel="\&quot;noopener" noreferrer\">harmless page</a>"}` for `sanitizeAllowAll` (allowing everything)

So, when only allowing some tags and attribute then `noreferrer`is removed. And anyway there is an unexpected `"` in the attribute value after `noopener`.

I cannot explain that and it causes some trouble for me.

(It might be a problem of html-parser, I did not check that. However, given the fact that changing sanitize-html parameters change the behavior I suspect that it is rather sanitze-html causing the issue here.)

**Comment by boutell** [comment]
sanitize-html sanitizes HTML strings, nothing else. If you want to sanitize attributes of JSON objects you will have to iterate the non-HTML parts yourself and pass the HTML strings to sanitize-html when and where appropriate.
