### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by skjo0c** [apostrophecms/sanitize-html#309]
I am trying to use `@matejmazur/react-katex` which give us a tag `<TeX></TeX>` but I am not able to get the latex value after passing the value in `sanitize-html`.

I will have something like this:

const html =
```
"<p>this is a test <TeX>this\thinspace is\thinspace a\thinspace test\thinspace \frac {1} {12}</TeX></p>";
```

I wanted an output like the following

![image](https://user-images.githubusercontent.com/20612562/67614991-0500fb80-f7e6-11e9-9abd-f8b6719d6fe6.png)

**Comment by boutell** [comment]
This module sanitizes only HTML and fragments thereof.
