### ISSUE TITLE
Allow an attribute on all allowedTags?

### ISSUE THREAD

**Issue by NorianNyx** [apostrophecms/sanitize-html#31]
Is anything like this currently supported? I know I can allowAttributes: false, but it seems this would allow some unwanted Attributes ('onclick' comes to mind), but I would like to add 'style' to the list of allowedAttributes for every allowedTag.

**Comment by cwill747** [comment]
So I took a crack at a veeeeeery basic implementation of the reworkcss/css parser into the sanitizer, and added only one sanitization option (removing @imports). You can see the progress here: [feat/cssparse](https://github.com/cwill747/sanitize-html/tree/feat/cssparse), specifically [this commit](https://github.com/cwill747/sanitize-html/commit/030dedf09fabd400674cecd9e17a84f2a48f313c). @boutell can you take a look?

**Comment by boutell** [comment]
Oh, now that's really interesting! Thanks for pursuing this.

Is the parser robust enough to understand all of the escape mechanisms that
might be used to pass bogus CSS?

On Tue, Jun 9, 2015 at 3:36 PM, Cameron Will <notifications@github.com>
wrote:

> So I took a crack at a veeeeeery basic implementation of the reworkcss/css
> parser into the sanitizer, and added only one sanitization option (removing
> @imports <https://github.com/imports>). You can see the progress here:
> feat/cssparse
> <https://github.com/cwill747/sanitize-html/tree/feat/cssparse>,
> specifically this commit
> <https://github.com/cwill747/sanitize-html/commit/030dedf09fabd400674cecd9e17a84f2a48f313c>.
> @boutell <https://github.com/boutell> can you take a look?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/31#issuecomment-110479298>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
(See Mikael's comment and links earlier.)

On Tue, Jun 9, 2015 at 3:49 PM, Tom Boutell <tom@punkave.com> wrote:

> Oh, now that's really interesting! Thanks for pursuing this.
>
> Is the parser robust enough to understand all of the escape mechanisms
> that might be used to pass bogus CSS?
>
> On Tue, Jun 9, 2015 at 3:36 PM, Cameron Will <notifications@github.com>
> wrote:
>
>> So I took a crack at a veeeeeery basic implementation of the
>> reworkcss/css parser into the sanitizer, and added only one sanitization
>> option (removing @imports <https://github.com/imports>). You can see the
>> progress here: feat/cssparse
>> <https://github.com/cwill747/sanitize-html/tree/feat/cssparse>,
>> specifically this commit
>> <https://github.com/cwill747/sanitize-html/commit/030dedf09fabd400674cecd9e17a84f2a48f313c>.
>> @boutell <https://github.com/boutell> can you take a look?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/sanitize-html/issues/31#issuecomment-110479298>
>> .
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by cwill747** [comment]
It seems to work okay, or fail completely if it thinks it's not valid CSS. See: http://iamdustan.com/reworkcss_ast_explorer/#/fXxvTEp526/1
