### ISSUE TITLE
transformTags - is it possible to get html element of tag?

### ISSUE THREAD

**Issue by asolopovas** [apostrophecms/sanitize-html#331]
Hi,

I have some bad html to sanitize, one of the problems I get is that some h2 tags contain like the whole paragraph, so I need to get the length of h2 tag that is being transformed and change it to p tag instead. Is there a way to achieve that with this library?

Thanks in advance.

**Comment by abea** [comment]
Check out the Transformations documentation. That might work for this. https://github.com/apostrophecms/sanitize-html#transformations. Though it looks like `transformTags` functions would need to be updated to include the text of the tag (maybe the whole frame?). That could be done in v1 or v2 depending on the implementation.
