### ISSUE TITLE
Sanitize Handlebars HTML Templates escaping partials

### ISSUE THREAD

**Issue by akshaykotadia** [apostrophecms/sanitize-html#341]
We are using this package to sanitize handlebars templates. Handlers has a concept of partials which works just like a macro. Here is how its supposed to be used https://handlebarsjs.com/guide/partials.html#basic-partials

Since it has a `>` sign to invoke the partials, sanitization is replacing `{{> myPartial}}` to `{{&gt; myPartial}}`and this breaks our template.
Is there a way to solve this or get around this problem ?

**Comment by boutell** [comment]
Handlebars templates are not HTML and are out of scope for this module. But, if you can write something to sanitize the handlebars bits, you can use this module to sanitize individual HTML sub-bits, perhaps.
