### ISSUE TITLE
I'm using sanitize-html only for sanitizing content from server side, but sanitzehtml gets in to client main bundle itself, please help on how to 1) not send to client or atleast 2) Not to be added to main bundle in Angular

### ISSUE THREAD

**Issue by wincyb** [apostrophecms/sanitize-html#345]

**Comment by boutell** [comment]
Hi @wincyb, sanitize-html really doesn't have any power over how you are building your project for front and back end. To put it another way, we couldn't force your frontend webpack build (I assume) to include it if we wanted to. What is happening presumably is that some module you are importing is importing sanitize-html as a prerequisite of its own. You'll need to figure out what module is responsible and get them to stop doing that or accept the requirement. But it's not something we can do anything about from here.
