### ISSUE TITLE
Typescript error: Sanitize not a function

### ISSUE THREAD

**Issue by wincyb** [apostrophecms/sanitize-html#346]
With Typescript if sanitize-html is used as dynamic module getting error. Had used @types/sanitize-html 1.22 version and sanitize-html version 1.23.0. Please let know how to fix.
const sanitizeHtml = await import('sanitize-html');
sanitizeHtml (a,b)-> 

 
Error: Uncaught (in promise): TypeError: sanitizeHtml is not a function TypeError: sanitizeHtml is not a function

**Comment by abea** [comment]
Please see the 2.x version, currently in the `v2` branch. That will be released in a beta version tomorrow.
