### ISSUE TITLE
Set discard option by tag

### ISSUE THREAD

**Issue by tstecca** [apostrophecms/sanitize-html#348]
Hello Sanitize-html.  Thank you very much for this excellent library.  I have opened two issues today both relating to a single problem that I am trying to solve. The other issue is #347. I apologize if this is bad form.  I will withdraw one if necessary.

We use sanitize-html to clean up some content that our company produces. Some of our content is Java Code and needs to display to the end-user as readable Java. In our mark-up it's always enclosed in a `<code class="language-java"><pre>Java code here</pre></code>` block. What is happening is that the content in that `<code>` block occasionally contains Java constructs that use a syntax like: < XXX >. When it goes through sanitize-html all I'm left with it " XXX ". I'd like to ignore the `code.language-java` tag. As you know there is a `disallowedTagsMode`. 
 We have it to discard. Is there a way to apply this discard option only on certain tags - like my `<pre>` tag?  My idea is that inside the `<pre>` tag sanitize-html would escape instead of discarding and let me keep my < Java > santax.

Thanks in advance for your help.

**Comment by boutell** [comment]
Per my note on the other ticket, you should check what is possible with various htmlparser2 module options passed through sanitize-html, but if not it is out of scope for this module.
