### ISSUE TITLE
dispaly wrong text when meet markdown syntax

### ISSUE THREAD

**Issue by MagicLeeW** [apostrophecms/sanitize-html#350]
‘[a link](link adress)[another link](another  link adress)’-->After the SanitizeHtml(string, {}) method is executed， the string  became '[a link]([link adress](link adress)) [another link](another  link adress)'
expected：[a link](link adress)[another link](another  link adress)

**Comment by boutell** [comment]
Markdown is not HTML so there is no expectation sanitize-html would respect it in any special way, however I admit I'm stumped as to why this string got modified at all. Want to send a PR with a failing unit test?

**Comment by MagicLeeW** [comment]
> Markdown is not HTML so there is no expectation sanitize-html would respect it in any special way, however I admit I'm stumped as to why this string got modified at all. Want to send a PR with a failing unit test?
@boutell hey sir, this is my usage.
const allowedTags = SanitizeHtml.defaults.allowedTags.concat([])
    return SanitizeHtml(text, {
      allowedTags       : difference(allowedTags, ['iframe']),
      allowedAttributes : extend({}, {
        a   : ['href', 'name', 'target'],
        img : ['src']
      }),
    })

**Comment by boutell** [comment]
I was not able to reproduce this issue using this code. Please submit a PR with a failing unit test so we can talk from the same code.
