### ISSUE TITLE
Would love a disallowedTags option

### ISSUE THREAD

**Issue by drewbaker** [apostrophecms/sanitize-html#351]
I want to enable all tags, except script tags. Whitelisting all allowed tags is now impossible with custom web components. So allowing us to opt out of dangerous tags would be super useful. Thanks!

**Comment by abea** [comment]
That seems totally reasonable. I think we'd be up for taking a PR on that. It would need to account for a situation where someone had the same tag in `allowedTags` and `disallowedTags`, and document that well. I'd probably think that `disallowedTags` should win in that case. It should also respect the `disallowedTagsMode`, of course.

**Comment by terret** [comment]
Also, it could be good for the `disallowedStyles`
