### ISSUE TITLE
1.22.0 update breaks IE11 compatibility

### ISSUE THREAD

**Issue by anton-kapelyushok** [apostrophecms/sanitize-html#363]
1.22.0 update introduces htmlparser2 ^4.0.0 dependency which depends on entities ^2.0.0 that contains regex unsupported by IE11
https://github.com/fb55/entities/blob/master/src/encode.ts#L65

**Comment by boutell** [comment]
This is a transitive dependency, it can't be fixed from here but you can follow the progress in the entities npm module:

https://github.com/fb55/entities/issues/209

You could pin that dependency in package-lock to 2.0.0 if necessary temporarily.

Leaving this open as I'm sure others will have the question.

**Comment by abea** [comment]
This is instigating us to look at planning a major version update that 1) changes the package `main` source to `index.js` directly and 2) provides a separate built version to allow people to continue using it as they are now. The OP issue _is_ from the dependency, but we can get around some of those issues by making it easier for people to `require` and build this as they need it.

**Comment by abea** [comment]
We've published the new major version, removing the build and switching `main` to `index.js`.
