### ISSUE TITLE
Sanitize-html removing all attributes inside <any_name> 

### ISSUE THREAD

**Issue by Poloten** [apostrophecms/sanitize-html#399]
It's possible to safe original attributes in tag ?

Original message: 
`=> #<Systemsession _id: 123, created_at: 2020-07-16 14:17:12 UTC, updated_at: 2020-08-12 14:15:27 UTC, systemuser_id: 123, phone: nil, lng: nil, lat: nil, deviceid: nil, mac: nil, devicename: nil, country: nil, city: nil, locations: nil, project_id: nil>`

Converted to:
`=&gt; #&lt;systemsession&gt;&lt;/systemsession&gt;`

Options:
```
text = sanitizeHtml(text, {
            allowedTags: ['b', 'u', 's', 'i', 'pre', 'code', 'q', 'blockquote', 'br', 'a'],
            selfClosing: ['br'],
            allowedAttributes: {
                a: ['href', 'target']
            },
            disallowedTagsMode: 'recursiveEscape'
        });
```

Expected message:

`=&gt; #&lt;Systemsession _id: 123, created_at: 2020-07-16 14:17:12 UTC, updated_at: 2020-08-12 14:15:27 UTC, systemuser_id: 123, phone: nil, lng: nil, lat: nil, deviceid: nil, mac: nil, devicename: nil, country: nil, city: nil, locations: nil, project_id: nil&gt;`

**Comment by boutell** [comment]
This is not HTML or even XML as far as I can tell, the syntax is different. This library is for sanitizing HTML. You could use it to sanitize things that behave exactly like HTML and use novel tags, although that's not an official use case, but it will never support parsing attributes that don't behave like HTML attributes.
