### ISSUE TITLE
Error after installing Library and calling the sanitizeHtml()

### ISSUE THREAD

**Issue by darshak-gosar** [apostrophecms/sanitize-html#431]
Hi,
Have you come across such issue shown below:
<img width="839" alt="Screen Shot 2020-10-13 at 7 52 47 PM" src="https://user-images.githubusercontent.com/62231989/95873642-be593800-0d8d-11eb-9e3a-bb39cd91814e.png">
After installing the Library and calling this sanitizeHtml function I am getting the error, Could you help me out ?

Thanks,
Darshak Gosar

**Comment by abea** [comment]
Not that I'm aware of. It looks like a deep depencency of postcss. I suggest reinstalling and making sure you're on the latest version.

**Comment by dennyluan** [comment]
Also running into this issue for versions beyond 1.21.

**Comment by abea** [comment]
It seems this was an issue in PostCSS that has been resolved. If not, please provide steps to reproduce.
