### ISSUE TITLE
How can I avoid tags which I don't want to transform

### ISSUE THREAD

**Issue by darshak-gosar** [apostrophecms/sanitize-html#433]
Hi,
I want to keep few tags as it is and not sanitize it, Is this Possible ?
eg: <b>hello</b> <%=welcome%> <strong>Sanitize-html</strong>
In the above example I want to keep <%=welcome%> as it is.

Thanks,
Darshak Gosar

**Comment by boutell** [comment]
This module is only intended to sanitize HTML. What you're describing is a template language, perhaps one that also allows markup. You'll need to use a parser for that template language.
