### ISSUE TITLE
past text from word and keep style and format

### ISSUE THREAD

**Issue by alainib** [apostrophecms/sanitize-html#434]
## The problem to solve

I'm adding a rich text editor to a ReactJs website using `slate-react`. I added  `sanitize-html` to clean text pasted from office document, it clean well but it remove all the style & formatting ( font size, bold , etc ).

Is there a way to transform word/office style to css for example ? 

thanks

**Comment by boutell** [comment]
See the `transformTags` option.

I would recommend approaching this by transforming things to classes, not by allowing CSS, which can make a mess more easily.
