### ISSUE TITLE
Function to check just URL

### ISSUE THREAD

**Issue by literakl** [apostrophecms/sanitize-html#442]
## The problem to solve

I use  this wonderful library to check the HTML code written by users. I added new feature - users can enter just URL in the input field and I will display it as a link. The library expects HTML code. 

## Proposed solution

New method sanitizeURL('javascript:xss') 

## Alternatives

The only workaround is to construct a link serverside, use sanitize method and extract URL to be stored.

**Comment by abea** [comment]
Would you elaborate on the flow of this feature? Is the argument passed in a URL or link HTML? And what is the returned value?

**Comment by literakl** [comment]
I just need to check if the URL is safe and I can use it. E.g. no hidden
JavaScript, XSS. The returned value should be true for safe URL and false
otherwise.

Dne po 23. 11. 2020 17:44 uživatel Alex Bea <notifications@github.com>
napsal:

**Comment by literakl** [comment]
My current code:

```
      const source = `<a href="${x}">XSS</a>`;
      const sanitized = sanitizeHtml(source, api.sanitizeConfigure());
      if (source !== sanitized) {
        logger.error(`XSS detected ${x}`);
        throw new Error('XSS detected');
      }
```

**Comment by abea** [comment]
That's certainly useful, but I don't think that's within the scope of what sanitize-html is meant to do. There are security benefits to it, but it's not primarily a security package per se. We also wouldn't have access to a parser that can do this without adding another significant dependency or trying to write it anew.

**Comment by literakl** [comment]
Hmm, but you already do this check for href attribute. I saw it in the
source code.

Dne út 24. 11. 2020 16:31 uživatel Alex Bea <notifications@github.com>
napsal:

**Comment by abea** [comment]
Yes, it checks for the _presence_ of the `href`, just like it does for any attribute. The only attributes where it parses the attribute values are classes and styles, which are fairly innocuous. Getting into security parsing is another thing altogether.

@boutell What do you think about opening up to community contributions for additional attribute value parsing?
