### ISSUE TITLE
Can we allow all tags inside a specific tag?

### ISSUE THREAD

**Issue by eladcandroid** [apostrophecms/sanitize-html#448]
Like allowing all tags inside code/pre tag. 
(To have a rich text editor with insert snippets support)

**Comment by abea** [comment]
A specific option to allow any code inside `code` or `pre` tags would be useful. It would need a bypass mechanism rather than trying to negotiate with `html-parser2`.

**Comment by boutell** [comment]
This would be a CSRF attack vector. Both "code" and "pre" allow tags to function normally inside them. The correct way to handle this is still to correctly escape characters when inside these tags, just as you would when inside any other tags.

**Comment by boutell** [comment]
(Sorry to be a bearer of bad news, I don't mean to be harsh here! But so far I don't see how this would be safe, and so it is better to send the message that you have to escape the usual suspects in code samples just as you do in any other text.)
