### ISSUE TITLE
Tags <ins> and <del> are not preserved when added to allowedTags

### ISSUE THREAD

**Issue by corinagum** [apostrophecms/sanitize-html#449]
## To Reproduce

```
const options = {
  allowedAttributes: {
    a: ['aria-label', 'href', 'name', 'rel', 'target', 'title'],
    img: ['alt', 'src']
  },
  allowedSchemes: ['data', 'http', 'https', 'ftp', 'mailto', 'sip', 'tel'],
  allowedTags: ['del', 'ins', 'etc...']
};
console.log(customMarkdownIt.render(sanitizeHTML('<ins>insert</ins> <del>delete</del>', options);
```
1. Run above code
2. Note result is `<p>insert delete</p>`

## Expected behavior
`<p><ins>insert</ins> <del>delete</del></p>`

## Describe the bug
Tags `<ins>` and `<del>` are filtered even when those tags are allowed to `allowedTags`.

## Details

**Version of Node.js:**
12.8.3

**Server Operating System:**
Windows

**Additional context:**
N/A

**Screenshots**
N/A

**Comment by abea** [comment]
`customMarkdownIt` is unrelated to this package. Please test again without that. I added those tags to the "should accept a custom list of allowed tags" test in the test suite and it worked fine.

**Comment by abea** [comment]
I see you fixed your project issue. Closing this.

**Comment by corinagum** [comment]
Hey sorry for the late reply, and for the confusion. Thought I did my due diligence and I was wrong. Thanks for taking a look.
