### ISSUE TITLE
Content after transformTags with text option is deleted

### ISSUE THREAD

**Issue by doncuomo** [apostrophecms/sanitize-html#463]
I changed the following spec in your code to reproduce the error:

  it('should replace text and attributes when they are changed by transforming function'

See the screenshot for my change:

<img width="725" alt="Screenshot 2021-02-03 at 09 51 49" src="https://user-images.githubusercontent.com/1198989/106722355-24502080-6606-11eb-8fd4-2ab7d0fa141e.png">

Test result:

<img width="1050" alt="Screenshot 2021-02-03 at 09 57 02" src="https://user-images.githubusercontent.com/1198989/106722399-3336d300-6606-11eb-98bb-280202656295.png">

I expect blaat to be in the result, but it's cut off

**Comment by kedarchandrayan** [comment]
@boutell, I tried with the snippet given in this issue. I got the expected result. Following are the findings.

code snippet:
```
const sanitizeHtml = require('sanitize-html');
a = sanitizeHtml('<a href="http://somelink">some text</a> blaat', {
	transformTags: {
		a: function(tagName, attribs) {
			return {
				tagName: tagName,
				attribs: attribs,
				text: 'somelinktext'
			};
		}
	}
})
```

Result obtained:
`<a href="http://somelink">somelinktext</a> blaat`

We can see that the result is the same as the expected result. I think we can close this issue, saying not reproducible anymore.

**Comment by boutell** [comment]
Thanks for testing.

**Comment by kedarchandrayan** [comment]
You’re welcome.
