### ISSUE TITLE
Opening angle followed by a letter is treated as start of a new tag

### ISSUE THREAD

**Issue by Metavirulent** [apostrophecms/sanitize-html#467]
## To Reproduce

```
const sanitize = require('sanitize-html');
const text = sanitize("we all know that one<two, isn't it?", {disallowedTagsMode: "escape"})
//outputs: we all know that one
```
## Expected behavior
Should output: we all know that one<two, isn't it?

## Describe the bug
It seems that the "<two" triggers an opening tag in the parsing but since there is no closing tag, the remainder of the string gets skipped.

## Details

**Version of Node.js:**
* v14.16.0 (but unrelated to bug)

**Server Operating System:**
* MacOS X but doesn't play a role here

**Comment by boutell** [comment]
The degree of tolerance for bad markup depends on the htmlparser2 module upon which sanitize-html is built. You could take up the issue there, but it's not wrong to treat this as an opening tag and disregard the rest of the string. `sanitize-html` is designed to sanitize valid HTML, not to guess at user intent in handwritten text with some HTML markup. The most common use case for sanitize-html is cleaning up valid but unwanted tags and attributes, for instance when pasted into a rich text editor or submitted maliciously by a script.
