### ISSUE TITLE
Unable to get 'src' attrib on iframe.

### ISSUE THREAD

**Issue by medinacharlesdan** [apostrophecms/sanitize-html#471]
## To Reproduce

Step by step instructions to reproduce the behavior:

`      sanitizeHtml(('<iframe width="560" height="315" src="https://www.youtube.com/" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'),
      {allowedTags: ["iframe"],
      allowedAttributes:{iframe:['*']}}
      )`

## Expected Output
`<iframe width="560" height="315" title="YouTube video player" frameborder="0" src="https://www.youtube.com/" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

## Describe the bug
> Not getting src attrib on iframe.
> output below:

`<iframe width="560" height="315" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

## Details

**Version of Sanitize-html**
> 2.3.3

**Comment by abea** [comment]
I added a test for this scenario and it does pass. Could you provide more information or a failing test?

```
  it('iframe test', function() {
    assert.equal(sanitizeHtml(('<iframe width="560" height="315" src="https://www.youtube.com/" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'), {
      allowedTags: [ 'iframe' ],
      allowedAttributes: { iframe: [ '*' ] }
    }), '<iframe width="560" height="315" src="https://www.youtube.com/" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>');
  });
```

Note that the exact expected output you list is not in the same order as the original markup.

**Comment by medinacharlesdan** [comment]
Closing this issue since I am not unable to replicate my current React Native - Expo setup that does not return the 'src' attr on an iframe tag, other than that It seems to return src attr. 

My solution for this was transforming iframe to embed:
`transformTags:{"iframe":"embed"}`
