### ISSUE TITLE
incompatible with Edge 18

### ISSUE THREAD

**Issue by girotrasanya** [apostrophecms/sanitize-html#477]
PLEASE NOTE: make sure the bug exists in the latest patch level of the project. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. Go to any application using sanitize-html on Edge 18 browser.
> 2. open console to see the error.

## Expected behavior
> page should load with no console error.

## Describe the bug
getting a blank page because of compilation error.
error:
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
ChunkLoadError: Loading chunk 1 failed

## Details

**Server Operating System:**
windows 10

**Browser:**
Edge 18

**Screenshots**
<img width="1177" alt="github_sanitize" src="https://user-images.githubusercontent.com/32578944/117972915-58e02080-b349-11eb-8768-8d96d2079aa1.png">

**Comment by abea** [comment]
sanitize-html isn't compiled and doesn't have a build. This seems more likely specific to your project. We will need more information about how you're using sanitize-html to help.
