### ISSUE TITLE
When using UglifyJs, there reports error; After using babel to transfer es6 to es5, there is anthor error

### ISSUE THREAD

**Issue by kikizl** [apostrophecms/sanitize-html#484]
When using UglifyJs, there reports error; After using babel to transfer es6 to es5, there is anthor error.

**Comment by boutell** [comment]
This module is anot an ES5 module. If it does not work properly with a particular pipeline for transpiling the code to ES5, then you will need to look at the issues you are having with that pipeline, which are probably not with sanitize-html itself.

As I recall, older versions of UglifyJs do not support ES5. Babel should support compilation to ES5, but issues with that pipeline aren't really in the scope of sanitize-html.
