### ISSUE TITLE
<img> in <figure> was accidentally removed

### ISSUE THREAD

**Issue by Glowin** [apostrophecms/sanitize-html#485]
## To Reproduce

Step by step instructions to reproduce the behavior:

``` js
sanitizeHtml('<figure class="wp-block-image size-large"><img loading="lazy" width="1024" height="482" src="https://www.split.io/wp-content/uploads/2021/03/Exp_event-blog-dashboard-1024x482.png?width=1024" alt="" class="wp-image-7617" srcset="https://www.split.io/wp-content/uploads/2021/03/Exp_event-blog-dashboard.png?width=1024&amp;dpr=2 2x, https://www.split.io/wp-content/uploads/2021/03/Exp_event-blog-dashboard.png?width=1024&amp;dpr=3 3x" /></figure>')
```

use default config.

output:

``` html
<figure></figure>
```

## Expected behavior

``` html
<figure><img src="https://www.split.io/wp-content/uploads/2021/03/Exp_event-blog-dashboard-1024x482.png?width=1024"></figure>
```

## Describe the bug
<img> in <figure> should not remove.

## Details

**Version of Node.js:**
v14.16.0

**Server Operating System:**
Mac OS X 11.2.3

**Additional context:**
> Add any other context about the problem here. If the problem is specific to a browser, OS or mobile device, specify which.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Comment by boutell** [comment]
`img` is not on the allowedTags list by default and you did not override it, so its removal is expected. Please reopen if you can reproduce this with `img` on the allowedTags list.

**Comment by Glowin** [comment]
@boutell Thanks for your answer,  problem solved. my new config is :

```
{
        allowedTags: sanitizeHtml.defaults.allowedTags.concat([ 'img' ]),
        allowedSchemes: sanitizeHtml.defaults.allowedSchemes.concat([ 'data' ]),
        allowedAttributes: {
            'img': ['src', 'alt'],
            'a': ['href']
        },
        allowedClasses: {
            'code': [ 'language-*', 'lang-*' ],
            'pre': [ 'language-*', 'lang-*' ]
        }
```
