### ISSUE TITLE
allow '!important' for style attributes

### ISSUE THREAD

**Issue by faxemaxee** [apostrophecms/sanitize-html#487]
Hey everyone,

I am currently trying to allow the important flag for CSS Attribute inside the style attribute for tags. I did not manage to get it work, the sanitizer always removes the '!important'.

Here is a code sandbox: https://codesandbox.io/s/wizardly-agnesi-64lc2?file=/src/index.js

I tried to use allowStyles but could not figure out the right config, the docs do not mention this specific case.

Looking forward to your answers!

Max

## Details

**Version of Node.js:**
14 LTS

**Server Operating System:**
Linux

**Comment by caub** [comment]
Same issue https://replit.com/@caub/sanitize-html-style-important-issue#index.js
