### ISSUE TITLE
Detecting nested media objects inside exclusiveFilter

### ISSUE THREAD

**Issue by wiscat** [apostrophecms/sanitize-html#490]
Hi,

Similar to this issue #313 , but dealing with nested images, is there any options to detect nested media objects, so to correctly sanitize empty ```<p>``` tags using ```exclusiveFilter``` and ```!frame.text.trim()```? 
```
<p>
   <a>
      <img />
   </a>
</p>
```

**Comment by abea** [comment]
There is the `mediaChildren` property as documented in the README. That might only apply to immediate children, so I'm not sure if it works for this. It sounds like something we'd be happy to review a PR for.
