### ISSUE TITLE
value of `undefined` returns unexpected `"undefined"`

### ISSUE THREAD

**Issue by shellscape** [apostrophecms/sanitize-html#502]
## To Reproduce

Step by step instructions to reproduce the behavior:

```js
var sanitizeHtml = require("sanitize-html")

sanitizeHtml(undefined)
// > "undefined"
```

## Expected behavior

I expected `undefined` to be returned

## Describe the bug

Since `undefined` itself is not a string and has to `toString`, it appears to be a bug that it's being turned into a string containing `"undefined"`. In most cases I'd wager that passing `undefined` means that a field, property, or value has been intentionally set to `undefined` and should be pass-through as there's no value there to operate on. There seems to be an assumption that the intent is to stringify `undefined` which is not a common pattern in JS.

`JSON.stringify(undefined)` returns plain `undefined` as well, and I would consider that to be the defacto standard. 

## Details

**Version of Node.js:** 14.15.3
**Server Operating System:** Amazon Linux / MacOS
**Additional context:**
**Screenshots**

**Comment by boutell** [comment]
Hi Shellscape, I don't mean to be inconsiderate of your use case. However this module already returns a string, and code that assumes a string will always be the result could actually crash if we changed that behavior. So for bc reasons this is not something we are really free to change. Whereas it is not difficult for you to wrap sanitize-html in a function that checks for undefined and returns undefined.

As for ecosystem normal behavior, the "validator" module is heavily used, and if you pass it undefined it throws an error, it doesn't return undefined:

https://www.npmjs.com/package/validator
