### ISSUE TITLE
Disallowed tags/attributes 

### ISSUE THREAD

**Issue by abhishekmatta999** [apostrophecms/sanitize-html#532]
There should be an option to add a list of disallowed tags/attributes.
According to my use case, I only want to remove "script" and "link" tags. I have to write all the other tags.

**Comment by adilmarjunior** [comment]
You can use exclusive filter.
```
sanitizeHtml(
  '<script></script><p>Some text</p>',
  {
    exclusiveFilter: function(frame) {
      return frame.tag === 'script'
    }
  }
);
```
