### ISSUE TITLE
img src whitelist

### ISSUE THREAD

**Issue by Umbranoxio** [apostrophecms/sanitize-html#539]
Is there a way to have a whitelist for image sources similar to allowedIframeHostnames? Mainly so users can't use their own image hosting service as some form of an IP grabber.

**Comment by GregCKrause** [comment]
I believe the exclusiveFilter can be used here. One option would be to check that img src URL regex matches target URL.

```js
const re = /^https?:\/\/(www\.)?example\.com\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)$/

sanitizeHtml(
  '<img src="https://example.com/media/12345" />',
  {
    exclusiveFilter: (frame) => {
      return frame.tag === 'img' && !re.test(frame.attribs.src)
    }
  }
);
```

Note, exclusiveFilter removes frames when return is `true`, and maintains frames with `false` returns.
