### ISSUE TITLE
attribute value filter is not supporting wildcard

### ISSUE THREAD

**Issue by TheFive** [apostrophecms/sanitize-html#561]
## To Reproduce

I have simply written a small testfile demonstration:
```javascript
const sanitizeHtml = require("sanitize-html");


const v = sanitizeHtml("<img src='/wp-content/upload/anicepicture.png'>", {
  allowedTags: sanitizeHtml.defaults.allowedTags.concat(["img"]),
  allowedAttributes: {
    img: [{
      name: "src",
      values: ["/wp-content*"]
    }]
  }
});
console.log(v);
```
result:
```
<img src />
```

## Expected behavior
i would expect the given img to be accepted and extended with closing

## Describe the bug
given <img> is filtered

## Details

**Version of Node.js:**
v16.14.2

**Server Operating System:**
Mac OSX

**Comment by boutell** [comment]
The documentation doesn't say there is support for wildcards for values, only for attribute names. This is not a bug.

Together with initially allowing any value for the attribute, you could use `transformTags` to achieve what you want.

**Comment by TheFive** [comment]
thanks for the answer, i will have a try.
