### ISSUE TITLE
Add attribute rel to default attributes

### ISSUE THREAD

**Issue by jonasgrilleres** [apostrophecms/sanitize-html#584]
It is recommended to add attribute: `rel="noopener, noreferrer"` to links opening in a new tab with attribute `target="_blank"`.  See [tabnabbing](https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#tabnabbing).

In the current situation, it is not possible to use `target` and `ref` attributes together without overriding `allowedAttributes` list.

Does it make sense to add `rel` attribute in the list of the defaults attributes? https://github.com/apostrophecms/sanitize-html/blob/795d079282bc4660e2d0740cf112ac6973aa77b1/index.js#L806

**Comment by Ami777** [comment]
```
 transformTags: {
   'a': sanitizeHtml.simpleTransform('a', {rel: 'noopener, noreferrer'})
 }
 ```
 
 💪

**Comment by danielnitu** [comment]
I ended up extending the default list, but it would be good to have `rel` included by default - or at least know why it's not included.

```ts
  const options = {
    allowedAttributes: {
      ...sanitize.defaults.allowedAttributes,
      a: ['href', 'name', 'target', 'rel'],
    },
  };

  const sanitizedHtml = sanitize(dirty, options)
```

**Comment by boutell** [comment]
I think a PR to add it would be reasonable. I don’t see a situation where
it would be considered harmful but target would not.
