### ISSUE TITLE
Is it possible to transform and wrap?

### ISSUE THREAD

**Issue by rob-rountree-cyted** [apostrophecms/sanitize-html#591]
Say my "dirty HTML" is a `<h3>Hello world!</h3>` element which I'd like transformed to the following:

`<p><span style="font-weight: bold;">Hello world!</span></p>`

How might I achieve that with `transformTags`, or is there another way?

**Comment by BoDonkey** [comment]
There isn't a good way to do this ( I don't believe) with sanitize-html. Have you looked into the [`cheerio`](https://github.com/cheeriojs/cheerio) package. It can handle nested tags.
Bob
