### ISSUE TITLE
Strip content / text, not just tags

### ISSUE THREAD

**Issue by tommedema** [apostrophecms/sanitize-html#60]
Currently when a tag is not allowed this results in a lot of (strange) text. E.g. a select box of country options would result in a long sentence of country names, if the option element is not allowed.

Is it possible to delete these tags entirely, including the contents / text?

**Comment by boutell** [comment]
I think it would make sense to beef up the nonTextTagsMap object to include
some more elements whose text should be discarded.

On Sat, Jul 4, 2015 at 3:04 PM, tommedema <notifications@github.com> wrote:

> Currently when a tag is not allowed this results in a lot of (strange)
> text. E.g. a select box of country options would result in a long sentence
> of country names, if the option element is not allowed.
>
> Is it possible to delete these tags entirely, including the contents /
> text?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/60>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
I'd accept a good pull request for that.

On Sat, Jul 4, 2015 at 4:45 PM, Tom Boutell <tom@punkave.com> wrote:

> I think it would make sense to beef up the nonTextTagsMap object to
> include some more elements whose text should be discarded.
>
> On Sat, Jul 4, 2015 at 3:04 PM, tommedema <notifications@github.com>
> wrote:
>
>> Currently when a tag is not allowed this results in a lot of (strange)
>> text. E.g. a select box of country options would result in a long sentence
>> of country names, if the option element is not allowed.
>>
>> Is it possible to delete these tags entirely, including the contents /
>> text?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/punkave/sanitize-html/issues/60>.
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
I just did this for textarea. You're reminding me that "option" might've been a good choice as well.
