### ISSUE TITLE
Applying styles to allowed class

### ISSUE THREAD

**Issue by jdozierezell** [apostrophecms/sanitize-html#602]
I'm trying to use sanitize-html on an input field but need to allow certain classes to be entered and to have their styles applied after sanitization. I'm using Astro, and simply including the class within the scoped style tag isn't working. My guess is that the scoping is messing with things. Is there a way to apply a style within the sanitize function, perhaps within transformTags? I've looked through the docs and only see an implementation for elements, so I'm wondering if this is possible. I'm using Node v19.2.0 on MacOS X

**Comment by BoDonkey** [comment]
It sounds to me like you are asking for two separate things. Santize is great for making sure that HTML is well formed and can transform the input HTML automatically. It sounds like you want to take the additional step of using the sanitized input. This sounds more like a case for JavaScript manipulation of the DOM, or... Maybe I'm wrong and you can add some additional details.
