### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by tyzion** [apostrophecms/sanitize-html#618]
Hi!
I wanted to know if it was possible to create a function which adds an html tag in a desired position or inside/outside a filtered tag.
I didn't find anything online or on you docs. Hope nothing slipped my search.

Anyway if this feature is not present, would it be possible to implement it?

Thanks guys!!

**Comment by boutell** [comment]
You can do a lot with the `transformTags` option, but if this doesn't meet your needs, your project might be more appropriate for the `cheerio` package. `cheerio` lets you manipulate a document server-side like jQuery would, which gives you a lot of flexibility for these use cases that go well beyond sanitization. You may wish to combine the two.

**Comment by tyzion** [comment]
Yeah I think I'll take a look into that, thanks!

**Comment by tyzion** [comment]
I used a combination of the 2 as you suggested, thank you very much!
And thanks a lot for this library!!
If it's out of scope, I'll close this issue

**Comment by ile** [comment]
Or domino https://github.com/fgnass/domino (instead of cheerio).

**Comment by boutell** [comment]
The domino docs say it is "not intended for untrusted code," which would make me a little nervous about using it for sanitization, at least without more understanding of what they mean by that.
