### ISSUE TITLE
Asynchronous transformTags call

### ISSUE THREAD

**Issue by Stanislavussov** [apostrophecms/sanitize-html#626]
Hi, I met problem in case when I want to make some API call inside transformTags function it never be awaited. As I understand `sanitize-html` does not support async calls in itself. Maybe somebody knows some workaround how to make it work?

Thanks

**Comment by boutell** [comment]
sanitize-html is meant to be a very fast library for sanitizing of user input. If you need to make API calls I suggest checking out something like `cheerio` which lets you load the document, manipulate it with a full jQuery-like API (but not just in the browser), and generate the HTML again when you're ready after doing whatever you wish.
