### ISSUE TITLE
README.md is reporting FAILED

### ISSUE THREAD

**Issue by alfreema** [apostrophecms/sanitize-html#627]
Not so much a bug, but the README.md is reporting FAILED.  Does this mean this package is not safe to use at this time due to some security or build concern?

![image](https://github.com/apostrophecms/sanitize-html/assets/34083554/a90dfebc-c078-41d5-8b5f-a35f8634d099)

**Comment by BoDonkey** [comment]
Hi @alfreema - this a relic left behind that we haven't gotten back to eliminate. We no longer make use of Circle CI and haven't eliminated the badge from all of our repos. This module is still tested using the internal mocha tests and dependencies are kept up to date. So despite to badge, the module is safe and available for use.
Cheers,
Bob

**Comment by boutell** [comment]
No, it's just that we are no longer using circleci, but of course this is messy, so it makes sense for us to fix this to use github CI actions. Issue should stay open.

**Comment by alfreema** [comment]
Maybe in the meantime, you should just remove or comment out line 3 of your README.md?
