### ISSUE TITLE
[Question] Best practice to cleanup HTML Spaghetti code

### ISSUE THREAD

**Issue by JpEncausse** [apostrophecms/sanitize-html#630]
## Question or comment

I need to cleanup a random HTML page to extract readable content. Modern website use A LOT of Spaghetti HTML. For instance : 

`<div> <div><div> <a href="/"> <div>Title of the site</div> </a> <div lazyload="event"><!--lazy <div class="headerPageHtml"><a href="/include/news.xml" target="_blank"><img id="socialRss" alt="access to rss" src="/asset/social/rss.png"></a></div></div></div>`

In this example I don't want all the `<div>`  and the formating `<div><img></div>` 
Should I strip all the <div> tags ? Or is there a clever way ?

**Comment by boutell** [comment]
It's unclear what you're trying to do exactly, but sanitize-html is quite good at keeping only the tags and attributes you approve, as you can see in the documentation. If you want to do more subtle things, there are transformation features. If your needs exceed that, then you might consider using `sanitize-html` as a first pass and then `cheerio` for the transformations.

**Comment by coreyward** [comment]
I came here to report a similar issue. An unclosed attribute (missing final double-quote) will cause everything from the start of that tag through to the end of the input to be stripped by `sanitize-html`. 

```
sanitize(`Hello, world. <a href="/this>this</a> is a demo of this behavior. <b>I won't be in the output!</b>`)
// => 'Hello, world. '
```

**Comment by coreyward** [comment]
@boutell Got it. So in the case of invalid HTML (the double quote never closes anywhere), is there any way to get an error back instead of having large portions of the input stripped out?

**Comment by boutell** [comment]
If you mean at the very end of the fragment, when you're absolutely sure no
closing quote is coming, it looks like htmlparser2 always tidies up at the
end by closing whatever isn't closed, and we're downstream of that. There
may or may not be htmlparser2 options that modify this behavior.

**Comment by coreyward** [comment]
Okay, I think we can live with that for now. Thank you!
