### ISSUE TITLE
Postcss vulnerability

### ISSUE THREAD

**Issue by wesleimarinho** [apostrophecms/sanitize-html#635]
When using this package, `npm audit` reports a vulnerability with Postcss:

![image](https://github.com/apostrophecms/sanitize-html/assets/30837062/01646e43-eef0-4e71-9d2d-6a97e325f31b)

**Comment by wesleimarinho** [comment]
I noticed a clean uninstall and install of the santiize-html fixes the vulnerability report.

**Comment by randompixel** [comment]
Do you think we could reopen this one? 

Snyk reports it as an issue down the dependency chain where https://github.com/Vannsl/vue-3-sanitize uses it and then I use vue3-sanitize. I'm not 100% on how yarn or Snyk determine which versions to use but explicitly setting this as > `8.4.25` in the root of the problem would surely help?

**Comment by boutell** [comment]
snyk looks at what's in your package-lock.json. `npm update` your project.

**Comment by randompixel** [comment]
Thanks @boutell I've tried a `yarn upgrade` to update the `yarn.lock` file but it didn't seem to fix it. I'll give it another go :(
