### ISSUE TITLE
travis-ci

### ISSUE THREAD

**Issue by ArtskydJ** [apostrophecms/sanitize-html#64]
First go to https://travis-ci.org/, log in with your github account, and enable the `sanitize-html` repo.

Then add the badge url to your README.md file:

``` md
[![Build Status](https://travis-ci.org/punkave/sanitize-htmlt.svg)](https://travis-ci.org/punkave/sanitize-html)
```

Then add a `.travis.yml` file:

``` yml
language: node_js
node_js:
  - "0.12"
  - "0.10"
  - iojs
```

Then commit and push.

Travis should build, and you'll see a ![Build Status](https://travis-ci.org/ArtskydJ/range-interval.svg?branch=master) badge on your readme!

**Comment by Rokt33r** [comment]
+1
It will make easy to contribute this project for other programmers.

**Comment by ArtskydJ** [comment]
> It will make easy to contribute this project for other programmers.

Yeah, it would. (Aside from enabling the repo on travis, you have to have push rights to do that.)

**Comment by boutell** [comment]
I imagine that list of node versions is out of date at this point

On Tue, Jan 5, 2016 at 9:37 AM, Joseph Dykstra <notifications@github.com>
wrote:

> It will make easy to contribute this project for other programmers.
>
> Yeah, it would. (Aside from enabling the repo on travis, you have to have
> push rights to do that.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/64#issuecomment-169018327>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by ArtskydJ** [comment]
Yeah, maybe this would be better:
```yml
language: node_js
node_js:
  - "stable"
  - "4.0"
  - "0.12"
  - "0.10"
```

**Comment by ArtskydJ** [comment]
@boutell If you log in to https://travis-ci.org with your github account, and flick the switch for the `sanitize-html` repo, I might be able to make the PR.

**Comment by ArtskydJ** [comment]
Looks like Circle CI was added, so I'm closing this issue.
