### ISSUE TITLE
Option to allow everything except dangerous tags/attributes

### ISSUE THREAD

**Issue by rChaoz** [apostrophecms/sanitize-html#671]
I would love to see an option to allow every tag except `<script>` or `<style>` and every non-event (`on*`) attribute (and [whatever else may be susceptible to XSS](https://stackoverflow.com/questions/6976053/xss-which-html-tags-and-attributes-can-trigger-javascript-events)). Right now the only option is to manually write every single tag and attribute manually, and it's impossible to allow custom tags unless you know them in advance.

## Proposal

Add two new config options: `disallowedTags` and `disallowedAttributes`. The first either is not allowed unless `allowedTags == false` or it takes precedence, but I think it makes sense for the latter to always be allowed:

```ts
{
  allowedAttributes: {
    "*": ["style"]
  },
  disallowedAttributes: {
    p: ["style"]
  }
}
```

So, in this case, the latter simply takes precedence.

**Comment by boutell** [comment]
This is a feature we've declined to add before because it is unsafe. New HTML elements are defined all the time, and if a new HTML element with security implications is defined, a site that was safe yesterday can be unsafe today. That's why it makes more sense to define the subset of HTML you want to allow.

**Comment by boutell** [comment]
Clarifying this is "not planned."

**Comment by boutell** [comment]
Clarifying this is "not planned."

**Comment by boutell** [comment]
(It looks like github won't let me update from "completed" to "not planned.")
