### ISSUE TITLE
Handling text with no markup

### ISSUE THREAD

**Issue by jolla56** [apostrophecms/sanitize-html#674]
I'm parsing a lot of old, bad html and sanitize-html is wonderful, but I have a problem I have not found a solution to. Sometimes there is text with no enclosing markup.
Is there a way to have sanitize-html to enclose text-nodes with no surrounding markup with <p></p>?

**Comment by boutell** [comment]
Are you speaking of text that is all the way at the root of the "document", outside of all enclosing tags altogether?

If you're dealing with fragments like that, you can handle it by wrapping the string like this before calling:

```
`<div>${myString}</div>`
```

Then you have a guaranteed outer wrapper `div`.

If you need a more sophisticated manipulation to happen here consider using the `cheerio` module.
