### ISSUE TITLE
Missing package-lock.json / yarn.lock

### ISSUE THREAD

**Issue by f0x52** [apostrophecms/sanitize-html#683]
It's recommended to Git check-in the lockfile for the Node.JS package manager your project using (npm or yarn). I noticed package-lock.json is specifically ignored in `.gitignore`

**Comment by boutell** [comment]
This is not recommened for libraries, only for applications. Since libraries' `package-lock` files are ignored when they are installed as dependencies of other projects, it would be misleading and confusing to check it in.

**Comment by f0x52** [comment]
I know it won't get published with the package, but isn't this still a valid usecase for people that work on the library through the git repo, like we're doing here?

**Comment by boutell** [comment]
No, because it would not accurately simulate what end users will get if they install the package in their project today. There is no point in committing an old package lock if it leads to tests passing (or failing) that wouldn't in the real world.
