### ISSUE TITLE
Support wildcards in allowedClasses configuration parameter

### ISSUE THREAD

**Issue by andrey-skl** [apostrophecms/sanitize-html#82]
It would be nice to have possibility to wildcard classes like already done in "Wildcards for attributes" feature

```
allowedClasses: {
   '*': ['test-class', 'some-prefixed-*']
}
```

**Comment by boutell** [comment]
It would. Want to do a pull request?

On Mon, Dec 7, 2015 at 11:04 AM, Andrey <notifications@github.com> wrote:

> Iw would be nice to have possibility to wildcard classes like already done
> in "Wildcards for attributes" feature
>
> allowedClasses: {
>    '*': ['test-class', 'some-prefixed-*']
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/82>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by huston007** [comment]
@boutell I'll check what I can do, thanks

**Comment by Rokt33r** [comment]
I made it. I hope it would be helpful. :dancer: 
https://github.com/Rokt33r/sanitize-html/commit/40571ce35c00933f0e99b7a653893026f71f7c0d

**Comment by felixfbecker** [comment]
@Rokt33r do you plan on submitting a pull request for that?
