### ISSUE TITLE
How to convert disallowed tags to entities?

### ISSUE THREAD

**Issue by zhaoyao91** [apostrophecms/sanitize-html#91]
so that `<p>hi</p>` can be converted to `&lt;p&gt;hi&lt;/p&gt;` instead of `hi`.

**Comment by BS-Harou** [comment]
Would also like to do this

**Comment by Charuru** [comment]
Same here.

**Comment by robertwbradford** [comment]
Has anyone found a good solution for this?

**Comment by abea** [comment]
This is now possible with the `disallowedTagsMode: 'escape'` option.
