### ISSUE TITLE
TypeScript version fork? remove `require` dependency...

### ISSUE THREAD

**Issue by NathanWalker** [apostrophecms/sanitize-html#99]
I may either fork or create a new repo based off this exact library but convert it to TypeScript and generate a definition file for it. This would make it nice to use with other TS projects.
That sound alright?

**Comment by boutell** [comment]
How is it not nice to use with TypeScript in its current form? Sounds like
a maintenance hassle without a benefit, but I don't know TypeScript.

On Wed, Mar 23, 2016 at 12:38 PM, Nathan Walker <notifications@github.com>
wrote:

> I may either fork or create a new repo based off this exact library but
> convert it to TypeScript and generate a definition file for it. This would
> make it nice to use with other TS projects.
> That sound alright?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/99>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by NathanWalker** [comment]
Well not that you *cannot* use it in it's current form. Having a `.d.ts` definition file makes it nice. :+1:

**Comment by NathanWalker** [comment]
But removing usage of `require` would be great since some TS build setups don't play nice with that.

**Comment by boutell** [comment]
What setups would those be? sanitize-html has some big dependencies, so
it's usually not a candidate to run in environments other than nodejs.

On Wed, Mar 23, 2016 at 1:31 PM, Nathan Walker <notifications@github.com>
wrote:

> But removing usage of require would be great since some TS build setups
> don't play nice with that.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/99#issuecomment-200455532>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by damienwebdev** [comment]
@NathanWalker just rely on https://www.npmjs.com/package/@types/sanitize-html.
